config/routes.rb
Rails.application.routes.draw do
  resources :notes
  #get 'home/index'
  get 'home/about'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: %i[ show edit update destroy ]

  # GET /notes or /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1 or /notes/1.json
  def show
    @notes = Note.all
  end

  # GET /notes/new
  def new
    @note = Note.new
    @notes = Note.all
  end

  # GET /notes/1/edit
  def edit
    @notes = Note.all
  end

  # POST /notes or /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to edit_note_path(@note), notice: "Note was successfully created." }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1 or /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to edit_note_path, notice: "Note was successfully updated." }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1 or /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: "Note was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:note_text,:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Your Day Plan', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Notes', notes_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'About', home_about_path, class:"nav-link" %>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About</h1>

app/views/home/index.html.erb
<h1>Hello World!</h1>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" href="/fontawesome/css/all.min.css">
  <title>Your Day Plan</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <%= render 'home/header' %>
  <%= yield %>
</body>
</html>

app/views/notes/_form.html.erb
<%= form_with(model: note) do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
        <% note.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div class="note-title">
      <p class="note-text">Title:</p>
      <%= form.text_area :title, class: "text-field-display" %>
    </div>
    <div  class="note-text">
      <p class="note-text">Note:</p>
      <%= form.text_area :note_text, class: "text-area-display" %>
    </div>
  </div>
  <div class="action">
    <%= form.submit class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<!--<%#= link_to 'Show', @note %> |-->
<%#= link_to 'Back', notes_path %>



<h1>Your Notes</h1>
<div class="container">
  <div class="row">
    <div class="col-2">
      <ul class="notes-list">
        <% @notes.each do |note| %>
          <li class="note">
            <%= link_to note.title, edit_note_path(note), class:"note-link" %>
            <div class="buttons-link-position">
              <%= link_to '<i class="fas fa-trash-alt"></i>'.html_safe, note,  class: "btn btn-secondary button-margin",  method: :delete, data: { confirm: 'Are you sure?' }%>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="col bg-note-text">
      <%= render 'form', note: @note %>
    </div>
  </div>
</div>
</div>
<%= link_to '<i class="fas fa-plus"></i>'.html_safe, new_note_path, class:"btn btn-secondary add-button" %>

app/views/notes/index.html.erb
<!--<p id="notice"><%#= notice %></p>-->

<!--<h1>Notes</h1>-->

<!--<table class="table">-->
<!--  <thead>-->
<!--    <tr>-->
<!--      <th>Note text</th>-->
<!--      <th>Title</th>-->
<!--      <th colspan="3"></th>-->
<!--    </tr>-->
<!--  </thead>-->

<!--  <tbody>-->
    <%# @notes.each do |note| %>
<!--      <tr>-->
<!--        <td><%#= note.note_text %>-->
<!--        <td><%#= note.title %>-->
<!--        <td><%#= link_to 'Show', note %></td>-->
<!--        <td><%#= link_to 'Edit', edit_note_path(note) %></td>-->
<!--        <td><%#= link_to 'Delete', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
<!--      </tr>-->
    <%# end %>
<!--  </tbody>-->
<!--</table>-->

<!--<br>-->


<h1>Your Notes</h1>
<div class="container">
  <div class="row justify-content-start">
    <div class="col-2">
      <ul class="notes-list">
        <% @notes.each do |note| %>
          <li class="note">
            <%= link_to note.title, edit_note_path(note), class:"note-link" %>
            <div class="buttons-link-position">
              <%= link_to '<i class="fas fa-trash-alt"></i>'.html_safe, note,  class: "btn btn-secondary button-margin",  method: :delete, data: { confirm: 'Are you sure?' }%>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="col bg-note-text">
    </div>
  </div>
</div>
</div>

<%= link_to '<i class="fas fa-plus"></i>'.html_safe, new_note_path, class:"btn btn-secondary add-button" %>

app/views/notes/new.html.erb
<!--<h1>New Note</h1>-->

<%#= render 'form', note: @note %>

<%#= link_to 'Back', notes_path %>


<h1>Create new note</h1>
<div class="container">
  <div class="row">
    <div class="col-2">
      <ul class="notes-list">
        <% @notes.each do |note| %>
          <li class="note">
            <%= link_to note.title, edit_note_path(note), class:"note-link" %>
            <div class="buttons-link-position">
              <%= link_to '<i class="fas fa-trash-alt"></i>'.html_safe, note,  class: "btn btn-secondary button-margin",  method: :delete, data: { confirm: 'Are you sure?' }%>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="col bg-note-text">
      <%= render 'form', note: @note %>
    </div>
  </div>
</div>
</div>
<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<!--<p id="notice"><%#= notice %></p>-->

<!--<p>-->
<!--  <strong>Note text:</strong>-->
  <%#= @note.note_text %>
<!--  <strong>Note title:</strong>-->
  <%#= @note.title %>
<!--</p>-->

<!--<%#= link_to 'Edit', edit_note_path(@note) %> |-->
<%#= link_to 'Back', notes_path %>



<h1>Your Notes</h1>
<div class="container">
  <div class="row">
    <div class="col-2">
      <ul class="notes-list">
        <% @notes.each do |note| %>
          <li class="note">
            <%= link_to note.title, edit_note_path(note), class:"note-link" %>
            <div class="buttons-link-position">
              <%= link_to '<i class="fas fa-trash-alt"></i>'.html_safe, note,  class: "btn btn-secondary button-margin",  method: :delete, data: { confirm: 'Are you sure?' }%>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="col bg-note-text">
      <div class="note-title">
        <%= @note.title %>
      </div>
      <div  class="note-text">
        <%= @note.note_text %>
      </div>
    </div>
  </div>
</div>
</div>
<%= link_to '<i class="fas fa-plus"></i>'.html_safe, new_note_path, class:"btn btn-secondary add-button" %>